version: "3"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./dbdata:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wpdata:/var/www/html
      - ~/projects/github/winlum/wordpress-campground-search:/var/www/html/wp-content/plugins/campground-search
    ports:
      - 8000:80
      - 8443:443
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
